/* eslint-disable react-hooks/set-state-in-effect */
import { useEffect, useState } from "react"; import { Link } from "react-router-dom"; import { Package, AlertTriangle, ShoppingCart, Wallet, Users, Clock3, ArrowUpRight, ArrowDownRight, RefreshCw } from "lucide-react"; import api from "../services/api";
const money = n => `৳${Number(n || 0).toLocaleString('en-BD', { maximumFractionDigits: 0 })}`;
export default function DashboardPage() {
    const [d, setD] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const load = async () => { setLoading(true); try { const { data } = await api.get('/dashboard'); setD(data); } catch (e) { setError(e.response?.data?.message || 'Could not load dashboard data.'); } finally { setLoading(false); } }; useEffect(() => { load(); }, []); if (loading) return <div className="loading-page"><RefreshCw className="spin" /> Loading your business overview...</div>; if (error) return <div className="error-panel"><h2>Dashboard unavailable</h2><p>{error}</p><button className="btn-secondary" onClick={load}>Try again</button></div>; return <div><div className="page-intro"><div><div className="eyebrow">BUSINESS OVERVIEW</div><h1>Greetings, {d.user?.name?.split(' ')[0] || 'there'}.</h1><p>Here’s what needs your attention today.</p></div><Link className="btn-primary" to="/app/place-order">+ Place new order</Link></div>
        <div className="metric-grid"><Metric icon={Wallet} label="Today's sales" value={money(d.todaySales)} note={`${d.salesChange >= 0 ? '+' : ''}${d.salesChange}% vs yesterday`} trend={d.salesChange >= 0} /><Metric icon={ShoppingCart} label="Today's orders" value={d.todayOrders} note={`${d.pendingOrders} pending`} trend={true} /><Metric icon={Package} label="Active products" value={d.activeProducts} note={`${d.totalProducts} total products`} /><Metric icon={AlertTriangle} label="Low stock" value={d.lowStock} note={d.lowStock ? 'Needs attention' : 'Stock looks healthy'} warning={!!d.lowStock} /></div>
        <div className="dashboard-main-grid"><section className="panel-card chart-panel"><div className="panel-title"><div><h2>Sales performance</h2><p>Last 7 days</p></div><Link to="/app/revenue">View revenue <ArrowUpRight size={15} /></Link></div><div className="sales-chart"><div className="y-labels"><span>৳{Math.round(d.chartMax / 1000)}k</span><span>৳{Math.round(d.chartMax / 2000)}k</span><span>৳0</span></div><div className="bars">{d.salesTrend.map(x => <div className="bar-col" key={x.label}><div className="bar" style={{ height: `${Math.max(5, (x.amount / d.chartMax) * 100)}%` }} title={money(x.amount)} /><span>{x.label}</span></div>)}</div></div></section><section className="panel-card"><div className="panel-title"><div><h2>Stock alerts</h2><p>Products at or below threshold</p></div><Link to="/app/inventory">View inventory</Link></div>{d.lowStockProducts.length ? <div className="alert-list">{d.lowStockProducts.slice(0, 5).map(p => <div className="alert-row" key={p.id}><div className="product-dot"><Package size={15} /></div><div><b>{p.name}</b><span>{p.sku}</span></div><strong>{p.stock_quantity} left</strong></div>)}</div> : <div className="empty-inline">No low-stock products. Nice work.</div>}</section></div>
        <div className="dashboard-bottom-grid"><section className="panel-card"><div className="panel-title"><div><h2>Recent orders</h2><p>Latest activity in your store</p></div><Link to="/app/orders">View all</Link></div><div className="table-wrap"><table><thead><tr><th>Order</th><th>Customer</th><th>Status</th><th>Total</th></tr></thead><tbody>{d.recentOrders.map(o => <tr key={o.id}><td><b>#{o.id}</b><small>{new Date(o.created_at).toLocaleDateString()}</small></td><td>{o.customer_name}</td><td><span className={`status ${String(o.status).toLowerCase()}`}>{o.status}</span></td><td><b>{money(o.total_amount)}</b></td></tr>)}</tbody></table>{!d.recentOrders.length && <div className="empty-inline">No orders yet.</div>}</div></section><section className="panel-card"><div className="panel-title"><div><h2>Top products</h2><p>By units sold</p></div><Link to="/app/products">Manage</Link></div><div className="top-products">{d.topProducts.map((p, i) => <div className="top-product" key={p.id}><span className="rank">{i + 1}</span><div><b>{p.name}</b><span>{p.units_sold} units sold</span></div><strong>{money(p.revenue)}</strong></div>)}{!d.topProducts.length && <div className="empty-inline">Sales data will appear here.</div>}</div></section></div>
        <div className="quick-row"><Link to="/app/products"><Package size={18} /> Add product</Link><Link to="/app/place-order"><ShoppingCart size={18} /> Create order</Link><Link to="/app/customers"><Users size={18} /> View customers</Link><Link to="/app/inventory"><Clock3 size={18} /> Stock history</Link></div></div>
}
function Metric({ icon: Icon, label, value, note, trend, warning }) { return <div className="metric-card"><div className="metric-icon"><Icon size={19} /></div><span>{label}</span><strong>{value}</strong><small className={warning ? 'warning-note' : trend === undefined ? '' : trend ? 'positive' : 'negative'}>{trend !== undefined && (trend ? <ArrowUpRight size={13} /> : <ArrowDownRight size={13} />)}{note}</small></div> }